theme: jekyll-theme-slate

title: "École Jeunes Chercheuses et Jeunes Chercheurs en Programmation (EJCP)"

description: "L'école du GDR GPL."

include: ['_pages', '_logos']
exclude: ['_config.yml', 'Makefile', 'Gemfile', 'Gemfile.lock']